{
 "title": "Gitlab MergeRequest Webhook",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(gitlab_mr_wh_gitlab_reqs{}, group) "
   }
  ]
 },
 "panels": [
  { "title": "Status (${group})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MergeRequest Events Received ",
   "type": "stat",
   "description": "Total number of merge request events received",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_events{group=~\"$group\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of Errors encountered handling the Merge Request Payload",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_errors[$__range]))"
    }
   ]
  },
  {
   "title": "Requests/Processed/Ignored Actions/Error Events",
   "type": "graph",
   "description": "Number of requests and processed events.",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_events{group=~\"$group\"}[$__rate_interval]))",
     "legendFormat": "Events Received"
    },
    {
     "expr": "sum(increase(gitlab_mr_wh_processed_mrs{group=~\"$group\"}[$__rate_interval]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(increase(gitlab_mr_wh_errors[$__range]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(increase(gitlab_mr_wh_ignore_actions{group=~\"$group\"}[$__interval]))",
     "legendFormat": "Events Ignored"
    }
   ]
  },
  {
   "title": "MergeRequests Processed",
   "type": "stat",
   "description": "Total number of merge request processed to add/remove reviewer",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_processed_mrs{group=~\"$group\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Alert Timeline",
   "type": "graph",
   "description": "Alerts (Pending/Firing) over time",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Pening (-) / Firing (+)" }
   ],
   "targets": [
    {
     "expr": "ALERTS{service=\"gitlab-mr-wh\"}",
     "legendFormat": "{{alertstate}} | {{severity}} | {{alertname}}"
    }
   ]
  },
  {
   "title": "Deployment ($group)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"})",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\", container!=\"POD\", pod=~\"gitlab-mr-wh-.*\"}[2m])) by (container)",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod)",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod)",
       "legendFormat": "Request"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (container)",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(kube_deployment_spec_replicas{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", deployment=\"gitlab-mr-wh\"}) by (deployment)",
       "legendFormat": "Replicas"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", deployment=\"gitlab-mr-wh\"}) by (deployment) / sum(kube_deployment_spec_replicas{job=\"kube-state-metrics\", namespace=\"gitlab-mr-wh\", deployment=\"gitlab-mr-wh\"}) by (deployment)",
       "legendFormat": "Replicas Available"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", deployment=\"gitlab-mr-wh\"}) by (deployment)",
       "legendFormat": "Replicas Unavailable"
      },
      {
       "expr": "kube_pod_info{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\"}"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}[5m])) by (pod, container)",
       "legendFormat": "Container Restarts"
      },
      {
       "expr": "kube_pod_container_status_running{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"} == 1",
       "legendFormat": "Status"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container)",
       "legendFormat": "CPU Request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container)",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}[5m])) by (pod, container)",
       "legendFormat": "CPU Usage"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}[5m])) by (pod, container)\n/ \nsum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container)",
       "legendFormat": "CPU Request Usage %"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container)",
       "legendFormat": "Mem Request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{job=\"kube-state-metrics\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container)",
       "legendFormat": "Mem Limit"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container) ",
       "legendFormat": "Mem Usage"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container) \n/ \nsum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container)",
       "legendFormat": "Mem Request Usage %"
      }
     ]
    }
   ]
  },
  { "title": "Application ($group)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Ignored MR Actions",
   "type": "graph",
   "description": "Payload Actions for the MR  which are ignored.\n\nmerge|approved",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_ignore_actions{group=~\"$group\"}[$__rate_interval])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Slack Messages Sent",
   "type": "graph",
   "description": "Number of slack messages sent",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_slack_msgs[$__rate_interval])) by (request, method)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Gitlab API Requests",
   "type": "graph",
   "description": "The number of API requests against Gitlab",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_gitlab_reqs{group=~\"$group\"}[$__rate_interval])) by (request, method)",
     "legendFormat": "{{request}} - {{method}}"
    }
   ]
  },
  {
   "title": "Removed Reviewer",
   "type": "graph",
   "description": "MR actions which caused review to be reset (set_to_wip)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_review_removed{group=~\"$group\"}[$__rate_interval])) by (group)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Errors encountered by the application.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_errors[$__rate_interval])) by (error)",
     "legendFormat": "{{request}} - {{method}}"
    }
   ]
  },
  {
   "title": "Slack Messages Errors",
   "type": "graph",
   "description": "Errors encountered when sending Slack Messages",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_slack_errors{group=~\"$group\"}[$__rate_interval])) by (request, method)",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}