{
 "title": "Gitlab MergeRequest Webhook",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MergeRequest Events Received ",
   "type": "stat",
   "description": "Total number of merge request events received ",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_events[$__range]))"
    }
   ]
  },
  {
   "title": "MergeRequests Processed",
   "type": "stat",
   "description": "Total number of merge request processed after passing gates",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_processed_mrs[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of Errors",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_errors[$__range]))"
    }
   ]
  },
  {
   "title": "Requests/Processed/Error Events",
   "type": "timeseries",
   "description": "Number of requests and processed events.",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_mr_wh_events[5m]))",
     "legendFormat": "MR Events Received"
    },
    {
     "expr": "sum(increase(gitlab_mr_wh_processed_mrs[5m]))",
     "legendFormat": " MRs Processed"
    },
    {
     "expr": "sum(increase(gitlab_mr_wh_errors[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "timeseries",
   "description": "Total Number of Workers and the number currently processing an MR.",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 1 },
   "targets": [
    { "expr": "gitlab_mr_wh_workers", "legendFormat": "Workers" },
    { "expr": "gitlab_mr_wh_workers_working", "legendFormat": "Working" }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "stat",
   "description": "Alerts Firing: Alerts which have met there threshold and time threshold",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (ALERTS{service=\"gitlab-mr-wh\", alertstate=\"firing\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "stat",
   "description": "Alerts Pending - Alerts have reached a threshold but not reached the time thereshold to fire.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (ALERTS{service=\"gitlab-mr-wh\", alertstate=\"pending\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "App: Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Errors encountered by the application.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_errors[5m])) by (error)",
       "legendFormat": "{{error}}"
      }
     ]
    }
   ]
  },
  {
   "title": "App: Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Read",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_cache_read{response=\"miss\"}[5m])) by (response, reason)",
       "legendFormat": "{{response}}/{{reason}}"
      },
      {
       "expr": "sum(increase(gitlab_mr_wh_cache_read{response=\"hit\"}[5m])) by (response)",
       "legendFormat": "{{response}}"
      }
     ]
    },
    {
     "title": "Cache Updates",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_cache_updates[5m]))",
       "legendFormat": "Updates"
      }
     ]
    },
    {
     "title": "Cache Admin UI",
     "type": "timeseries",
     "description": "Cache Admin UI Requests",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_cache_admin[5m]))",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Cache Clears/Deletes",
     "type": "timeseries",
     "description": "Clear/Delete a cache entry from the Admin UI.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_cache_clear[5m]))",
       "legendFormat": "Clears"
      },
      {
       "expr": "sum(increase(gitlab_mr_wh_cache_delete[5m]))",
       "legendFormat": "Deletes"
      }
     ]
    }
   ]
  },
  {
   "title": "App: Gitlab",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gitlab MR Events",
     "type": "timeseries",
     "description": "Events calling the Webhook from Gitlab",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_events[5m])) by (group, type)",
       "legendFormat": "{{group}} - {{type}}"
      }
     ]
    },
    {
     "title": "Gitlab API Requests",
     "type": "timeseries",
     "description": "The number of API requests against Gitlab",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_gitlab_reqs[5m])) by (group, request, method)",
       "legendFormat": "{{group}} - {{request}} - {{method}}"
      }
     ]
    },
    {
     "title": "Processed MRs",
     "type": "timeseries",
     "description": "Events which passed initial tests and were processed for assinging reviewers",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_processed_mrs[5m])) by (group)",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Set to WIP (Reviewer Removed)",
     "type": "timeseries",
     "description": "Set an MR to WIP and therefore had reviewer removed.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_review_removed[5m])) by (group)",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "MR Events Ignored/Failed",
     "type": "timeseries",
     "description": "MR Events which are in a state of unreadiness for review and therefore not assigned an MR",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_ignore_actions[5m])) by (group, action)",
       "legendFormat": "{{group}} - {{action}}"
      }
     ]
    },
    {
     "title": "Recursive Calls",
     "type": "timeseries",
     "description": "Application updating an MR which in turn calls itself, the application will ignore this request.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_recursive_calls[5m])) by (group)",
       "legendFormat": "{{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "App: Slack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slack Messages Sent",
     "type": "timeseries",
     "description": "Number of slack messages sent",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_slack_msgs[5m])) by (group, channel)",
       "legendFormat": "Message: {{group}} - {{channel}}"
      },
      {
       "expr": "sum(increase(gitlab_mr_wh_slack_msgs_errors[5m])) by (group, channel, error)",
       "legendFormat": "Error: {{group}} - {{channel}} - {{error}}"
      }
     ]
    },
    {
     "title": "Slack API Requests",
     "type": "timeseries",
     "description": "Number of slack api requests for user data.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_slack_api_reqs[5m])) by (request)",
       "legendFormat": "Request: {{request}}"
      },
      {
       "expr": "sum(increase(gitlab_mr_wh_slack_api_errors[5m])) by (request, error)",
       "legendFormat": "Error: {{request}} - {{error}}"
      }
     ]
    },
    {
     "title": "Unexpected Conditions",
     "type": "timeseries",
     "description": "Types of Error to do with config, not actual application errors.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(gitlab_mr_wh_no_matching_slack_user[5m])) by (group)",
       "legendFormat": "No Matching Slack User: {{group}}"
      },
      {
       "expr": "sum(increase(gitlab_mr_wh_slack_status_unavailable[5m])) by (group, reason)",
       "legendFormat": "Slack Status Unavailable: {{group}} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alert Timeline",
     "type": "graph",
     "description": "Alerts (Pending/Firing) over time",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Pening (-) / Firing (+)" }
     ],
     "targets": [
      {
       "expr": "ALERTS{service=\"gitlab-mr-wh\"}",
       "legendFormat": "{{alertstate}} | {{severity}} | {{alertname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Resource",
     "type": "timeseries",
     "description": "CPU usage and resource requests in the namespace\n\nTotal Pod CPU usage is an estimate that includes both kernel and user space usage.\n\nAllocated is the percentage of the CPU request quota that has been allocated to pods in the namespace.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}[2m])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (container)",
       "legendFormat": "Limits"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (container) ",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Memory Resource",
     "type": "timeseries",
     "description": "Memory usage and resource requests in the namespace\n\nMemory usage of the pods is from \"Working Set\", this excludes things like disk cache that can be evicted from resident memory.\n\nAllocated is the percentage of the resource quota memory request that has been allocated to pods.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container) ",
       "legendFormat": "{{pod}} Total"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (container) ",
       "legendFormat": "Limits"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (container)",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container) ",
       "legendFormat": "{{pod}} Working Set"
      }
     ]
    },
    {
     "title": "Memory Resource (Breakdown)",
     "type": "timeseries",
     "description": "Memory usage and resource requests in the namespace\n\nMemory usage of the pods is from \"Working Set\", this excludes things like disk cache that can be evicted from resident memory.\n\nAllocated is the percentage of the resource quota memory request that has been allocated to pods.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (container) ",
       "legendFormat": "Limits"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (container)",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(container_memory_rss{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container)",
       "legendFormat": "{{pod}} RSS"
      },
      {
       "expr": "sum(container_memory_cache{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container)",
       "legendFormat": "{{pod}} Cache"
      },
      {
       "expr": "sum(container_memory_swap{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container=\"gitlab-mr-wh\"}) by (pod, container)",
       "legendFormat": "{{pod}} Swap"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployments",
     "type": "table",
     "description": "Does not include Thanos Sidecar which runs in the Promethues Pods",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(kube_deployment_spec_replicas{namespace=~\"gitlab-mr-wh-.*\", deployment=\"gitlab-mr-wh\"}) by (deployment)",
       "legendFormat": "Replicas"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"gitlab-mr-wh-.*\", deployment=\"gitlab-mr-wh\"}) by (deployment) \n/ \nsum(kube_deployment_spec_replicas{namespace=~\"gitlab-mr-wh-.*\", deployment=\"gitlab-mr-wh\"}) by (deployment)",
       "legendFormat": "Replicas Available"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"gitlab-mr-wh-.*\", deployment=\"gitlab-mr-wh\"}) by (deployment)",
       "legendFormat": "Replicas Unavailable"
      },
      {
       "expr": "kube_pod_info{pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}"
      },
      {
       "expr": "max(kube_deployment_labels{deployment=\"gitlab-mr-wh\"}) without (pod)"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "table",
     "description": "Does not include Thanos Sidecar which runs in the Promethues Pods\n\nCPU Request Usage shows the percentage of utilisation against the request value. The application can go beyond this to the limit.\n\nMemory usage is split between the working set, rss and usage (which includes filesystem cache) and compares against limits. Whilst working set and rss are indicators of potential OOM killing the usage metric is only for considerations of performance.\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}[5m])) by (pod, container)",
       "legendFormat": "Container Restarts"
      },
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container) == 1",
       "legendFormat": "Status"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container)",
       "legendFormat": "CPU Request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container)",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}[5m])) by (pod, container)",
       "legendFormat": "CPU Usage"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}[5m])) by (pod, container)\n/ \nsum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container)",
       "legendFormat": "CPU Request Usage %"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container)",
       "legendFormat": "Mem Request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container)",
       "legendFormat": "Mem Limit"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container) ",
       "legendFormat": "Mem Usage (working set)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container) \n/ \nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container)",
       "legendFormat": "Mem Usage (working set) %"
      },
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container) ",
       "legendFormat": "Mem Usage (Evictable Cache)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container) \n/ \nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container)",
       "legendFormat": "Mem Usage (Evictable Cache) %"
      },
      {
       "expr": "sum(container_memory_rss{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container) ",
       "legendFormat": "Mem Usage (RSS)"
      },
      {
       "expr": "sum(container_memory_rss{namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container) \n/ \nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"gitlab-mr-wh-.*\", pod=~\"gitlab-mr-wh-.*\", container!~\"(|POD)\"}) by (pod, container)",
       "legendFormat": "Mem Usage (RSS) %"
      }
     ]
    }
   ]
  }
 ]
}